name: Check Lint
on: 
  pull_request:
    branches: 
      - master
jobs:
  checkLint:
    runs-on: ubuntu-latest
    steps:
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}


